var mongoose = require('mongoose');

var docoutSchema = new mongoose.Schema({
    property:{type:mongoose.Schema.Types.ObjectId,ref:'Property'},
    user:{type:mongoose.Schema.Types.ObjectId, ref:'User'},
    createdAt:{type:Date,default:Date.now()},
    address:{
        street1:{type:String},
        street2:{type:String},
        city:{type:String},
        county:{type:String},
        state:{type:String},
        zip:{type:String}
    },
    borrower:{
        name:{
            last:{type:String},
            first:{type:String},
            middle:{type:String},
            suffix:{type:String}
        }
    },
    coborrower:{
        name:{
            last:{type:String},
            first:{type:String},
            middle:{type:String},
            suffix:{type:String}
        }
    },
    lender:{type:String},
    loanType:{
        type:String,
        enum:['Refi','Purchase']
    },
    product:{
        forward:{
            which:{
                type:String,
                enum:['Conv','Jumbo','FHA','VA']
            },
            streamline:{
                type:String,
                enum:['Yes','No']
            },
            startRate:{
                type:String
            },
            escrow:{
                type:String,
                enum:['Yes','No']
            },
            ltv:{
                type:String
            },
            cltv:{
                type:String
            },
            term:{
                type:String
            },
            armTerm:{
                type:String
            }
        },
        reverse:{
            which:{
                type:String,
                enum:['FTR','H2H','Adjustable','Fixed']
            },
            margin:{
                type:String,
            }
        }
    },
    loan:{
        amount:{
            type:String
        },
        balance:{
            type:String
        }
    },
    fee:{
        front:{
            type:String
        },
        back:{
            type:String,
        }
    },
    leadType:{
        type:String,
        enum:['Dialer','Personal Mailer','Company Mailer','Cold Call','Referral']
    },
    docsDelivery:{
        type:String,
        enum:['UPS Delivery','Email','Faxed','LO Face to Face','Notary']
    },
    expectedDeliveryDate:{
        type:{type:Date}
    },
    notes:{
        type:String
    }
}, {
    timestamps:true
});

module.exports = mongoose.model('DocOut', docoutSchema);